name: 🔄 Автообновление сайта и данных

on:
  schedule:
    # Проверяем каждые 5 минут
    - cron: '*/5 * * * *'
  workflow_dispatch:  # Можно запустить вручную

jobs:
  auto-update:
    runs-on: ubuntu-latest
    steps:
      - name: 🔁 Клонировать репозиторий
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: 📂 Проверить и создать файлы, если их нет
        run: |
          mkdir -p .github/workflows
          touch news.json reviews.json
          echo "[]" > news.json
          echo "[]" > reviews.json
        continue-on-error: true

      - name: 🕵️ Проверить изменения
        id: check-changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          # Добавляем все файлы
          git add .

          # Проверяем, есть ли изменения
          if git diff-index --quiet HEAD --; then
            echo "❌ Нет изменений — выходим."
            exit 78  # no-op
          else
            echo "✅ Обнаружены изменения — фиксируем."
            echo "has_changes=true" >> $GITHUB_OUTPUT
          fi

      - name: 💾 Зафиксировать и отправить
        if: ${{ steps.check-changes.outputs.has_changes == 'true' }}
        run: |
          git add .
          git commit -m "🔄 Автообновление: $(date '+%d.%m.%Y %H:%M') — news.json, reviews.json, index.html"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
