name: Update News from Bot

on:
  workflow_dispatch:  # Запускается вручную или через API
  repository_dispatch:  # Для внешних триггеров
    types: [new_news]

jobs:
  update-news:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Update news on website
      run: |
        echo "🔄 Обновление новостей на сайте..."
        python .github/scripts/update_news.py
        
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "🤖 Автоматическое обновление новостей" || exit 0
        git push
